import { Story } from '@/lib/types/content'

export const story: Story = {
  id: 'from-the-streets-to-dreams-a-journey-of-perseverance-and-purpose',
  title: 'From Streets to Dreams: Meet Thuso',
  slug: 'from-the-streets-to-dreams-a-journey-of-perseverance-and-purpose',
  category: 'Impact Story',
  excerpt: 'Thuso Pejane shares a journey from Rockville, Soweto to Stellenbosch, driven by education, football, and the will to build a future.',
  content: `My name is Thuso Pejane from Rockville (Soweto), south of Johannesburg. A place where having enough to eat was never a guarantee. I was raised by a single mother who was a domestic worker. I knew that education was the only ticket out of this cycle of struggle, that is why my family was so proud when I completed my diploma in Accounting and Estate administration back home. Football gave me hope, happiness and for a short moment I also thought of pursing it to a professional level. Studies and football were the only hope to drive me out of the hardship also to improve the standard of living at home.

In January 2023, I left everything behind, and I moved to Stellenbosch with nothing but a dream. Stellenbosch is where many successful stories began, and I was determined to make mine one of them. Life at this moment was really a gamble because I wanted to study but missing the deadline of applications limited my chances of being accepted. I didn’t know anyone, I couldn’t speak Xhosa or Afrikaans, and I had no place to stay, little did I know that my journey would become a beautiful struggle, one that would test everything that I thought I knew about my ambition and perseverance.

I arrived at the university with only R800 in my pocket which was barely enough to rent a shack. I was told the school was closed for the day. A kind receptionist offered me a place to stay for a night, which was a small relief. The following day I went to submit my walk-in application, but I was placed on a waiting list. My future was uncertain about what would happen next: What if I don’t get accepted at the university, How am I going to sustain myself? I scrambled to find a place to stay. Through the receptionist’s landlord, I found a room that cost double of what I had in my pocket. My food budget for the month was R50 and I went days without food, sometimes surviving on a single apple or pack of R1 chips. Despite the hunger, I walked for hours every day searching for work. I used these words to reflect on my day at night, “Tomorrow will be a better day”.

Joining the World of Work program at Pinotage Youth Development Academy (PYDA) and learning crucial job-hunting skills turned to be a crucial step of my life as my walk-in application at the university was not successful. My financial struggles continued. On Sundays I would be depended on a morning coffee with a cookie from church and that would be my only meal for the day, but I kept my words in mind that: Tomorrow it will be a better day. After two months of unpaid rent, I finally got a call from Seattle Coffee Co. My hard work paid off and I was offered the job as a barista. But as I was preparing to celebrate this good news, the house that I was renting was sold and there were few hours to move out. I found myself with a job but without a place to stay. I slept on the streets for two days until Simon, the street photographer, offered me a place to stay in a squatter camp shack. Despite the tough living conditions of rain flooding the shack and sleepless nights. I focused on my training and my first payment allowed me to rent a room on my own taking the first step towards beginning a new chapter of my life where I could breathe easier and start rebuilding my life.

I used my lunch breaks to visit PYDA to equip myself with data analysis skill. This was the moment where I was introduced to Nico De Klerk, the founder of the StreetBiz Foundation which established the Be a Nelson Programme. I was attracted by the initiative and opportunities that they provide like social entrepreneurship courses, a mentorship, and a global networking to empower marginalised youth. In March 2024, I had the opportunity to be part of the MasterPeace South Africa walk, surrounded by breathtaking scenery of coastal area of the Indian Ocean, and inspired by like-minded individuals. The Walk gave me hope, courage and belief that anyone regardless of their background or colour can achieve greatness. I felt valued, appreciated, and I forgot about race or my background from the first moment to the last one. It might have been the combination of vibrant discussions and silent walks along the ocean that shaped my idea of developing ResPlek, The first ever Student Accommodation App in South Africa. ResPlek aims to simplify the search and bookings of students accommodation.

Through the network I built during the Walk, support is provided that is needed taking me one step closer to my new dream which is ResPlek. ResPleks ambition is to provide verified accommodation to students while pursuing their studies. With ResPlek my goal is to end accommodation scams and to offer support to the youth by providing service with integrity. ResPlek is near completion with only IT and the legal part delaying the process, but the aim is to launch it in first half of 2025. The skills that I gained in website development along the connections that I made really transformed my life. From streets to Dreams, my journey has been a beautiful struggle, proving that through chaos, positivity, and perseverance one can turn ideas into reality.`,
  featured_image: '/images/stories/from-the-streets-to-dreams-a-journey-of-perseverance-and-purpose.png',
  publish_date: '2024-10-02T14:40:30.000Z',
  is_featured: false,
  nelson_slug: 'thuso-pejane'
}
